# Needed because we don't fully qualify all R references in the codebase (we use R.id instead of com.gpl.rpg.AndorsTrail.R.id... )
android.enableNonTransitiveRClass=false# AGP 9 creates unit test tasks only for the tested build type (debug). CI also runs
# testReleaseUnitTest, which tests the code paths of release builds.
android.onlyEnableUnitTestForTheTestedBuildType=false
